# -*- coding: utf-8 -*-
"""Aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12OvP63a66OJ_m-NaRSf4HwanXTqF8LyM
"""

import pandas as pd
dados = pd.read_csv("https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv")
dados

dados.head()

dados.sample(10)

dados.info()

dados["Bairro"][6522]

dados.Metragem.mean()

tem_imoveis_vila = (dados["Bairro"]=="Vila Mariana")
tem_imoveis_vila

imoveis_vila_mariana=dados[tem_imoveis_vila]
imoveis_vila_mariana

imoveis_vila_mariana["Metragem"].mean()

dados["Bairro"].value_counts()

n_imoveis_bairro = dados["Bairro"].value_counts()
n_imoveis_bairro.head(10).plot.bar()

imoveis_bairro = dados["Bairro"].value_counts()
imoveis_metragem = dados['Metragem']
imoveis_metragem