# -*- coding: utf-8 -*-
"""Aula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12OvP63a66OJ_m-NaRSf4HwanXTqF8LyM
"""

import pandas as pd
dados = pd.read_csv("https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv")
dados

dados.head()

dados.sample(10)

dados.info()

dados["Bairro"][6522]

dados.Metragem.mean()

tem_imoveis_vila = (dados["Bairro"]=="Vila Mariana")
tem_imoveis_vila

imoveis_vila_mariana=dados[tem_imoveis_vila]
imoveis_vila_mariana

imoveis_vila_mariana["Metragem"].mean()

dados["Bairro"].value_counts()

n_imoveis_bairro = dados["Bairro"].value_counts()
n_imoveis_bairro.head(10).plot.bar()

dados.head()

dados['Valor'].str.split(expand=True)

dados['Valor'].str.split(expand=True)[0].unique()

dados[['Moeda','Valor_anuncio','Tipo_anuncio']] = dados['Valor'].str.split(expand=True)
dados.head()

dados[dados['Tipo_anuncio'].isnull()]

dados_vendas = dados[dados['Tipo_anuncio'].isnull()]
dados_vendas

dados_vendas["Valor_anuncio"].str.replace(".","").astype(float)

dados_vendas["Valor_anuncio_float"] = dados_vendas["Valor_anuncio"].str.replace(".","").astype(float)

dados_vendas

dados_vendas["Valor_anuncio_float"].plot.hist(bins=50)

pd.set_option("display.precision",2)
pd.set_option("display.float_format",lambda x: '%.2f' % x)
dados_vendas.describe(include = "all")

dados_vendas.describe()

import seaborn as sns
import matplotlib.pyplot as plt

sns.set()
plt.figure(figsize = (10,8))
ax = sns.histplot(data = dados_vendas, x = "Valor_anuncio_float",kde=True)
ax.set_title("Histograma Valor Imóvel")
plt.xlim((-50,10000000))
plt.show()